### PR TITLE
FIX: Error modal when dragging uploaded images

### LINKED ISSUE #58: Moving images throws an error alert but nothing is actually broken
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

When i try to move an image that has already been uploaded/embedded, it gives this error although there's nothing really wrong with the image: 

screen shot 2016-10-26 at 10 12 04 am

### PR DESCRIPTION
**Pull request by VladimirMikulic**
Dragging uploaded images would trigger an error modal.
With this change, images that are uploaded are not draggable and won't throw an error.

I also thought about performance, this will only select images that are draggable(newly uploaded images) and it won't select all images in the textarea.

ezgif com-video-to-gif (5)

Resolves #58 

@jywarren @IshaGupta18 @sagarpreet-chadha could you review this? Thanks.

### CODE REVIEW

File: src/core/Util.js [hunk 1]
```diff
@@ -104,6 +104,30 @@ module.exports = {
...
+        self.enableScroll();
+      }
+
+      var imageElements = document.querySelectorAll(
+        '.wk-wysiwyg img:not([draggable="false"])'
+      );
+
+      imageElements.forEach(imageElement => {
+        imageElement.setAttribute("draggable", "false");
+      });
```
Comment (VladimirMikulic) [inline src/core/Util.js]: These 3 lines seem to cause 'ReferenceError: Can't find variable: PL'. I don't have any idea why that happens.

Comment (VladimirMikulic) [reply src/core/Util.js]: Arrow function, right...

**Comment by VladimirMikulic** [comment]
Alright, this is ready for merge.

**Comment by jywarren** [comment]
Really nice, thank you!!!

**Comment by VladimirMikulic** [comment]
You're welcome :)
