### PR TITLE
Fix toolbar float_start error in plots2

### LINKED ISSUE #599: toolbar starts floating before rich text area in plots2
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
Fixes #599 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
@sagarpreet-chadha @jywarren please review

File: src/modules/PublicLab.RichTextModule.js [hunk 1]
```diff
@@ -310,15 +310,15 @@ module.exports = PublicLab.RichTextModule = PublicLab.Module.extend({
     var wkC = document.getElementsByClassName("wk-commands")[0];
 
     $(window).scroll(function() {
-      var textAreaRect = document
-          .getElementsByClassName("wk-container")[0]
+      var textAreaRect = $(".ple-textarea")[0]
```
Comment (jywarren) [inline src/modules/PublicLab.RichTextModule.js:313]: Nice!

File: src/modules/PublicLab.RichTextModule.js [hunk 2]
```diff
@@ -310,15 +310,15 @@ module.exports = PublicLab.RichTextModule = PublicLab.Module.extend({
...
-      var footerRect = document
-          .getElementsByClassName("ple-footer")[0]
+      var richAreaRect = $(".wk-wysiwyg")[0]
+          .getBoundingClientRect();
+      var footerRect = $("ple-footer")[0]
           .getBoundingClientRect().height;
 
       if (
-        textAreaRect.bottom >= ((window.innerHeight || document.documentElement.clientHeight) - footerRect) && textAreaRect.top <= ((window.innerHeight || document.documentElement.clientHeight) - footerRect)
+        (textAreaRect.bottom || richAreaRect.bottom) >= ((window.innerHeight || document.documentElement.clientHeight) - footerRect) && (textAreaRect.top || richAreaRect.top) <= ((window.innerHeight || document.documentElement.clientHeight) - footerRect)
```
Comment (jywarren) [inline src/modules/PublicLab.RichTextModule.js:321]: Awesome. OK, now let's see why it's not passing tests. Maybe it was just a timeout or something.

**Comment by jywarren** [comment]
Oh hmm. Error is:

```
     ReferenceError: Can't find variable: PL in file:///home/travis/build/publiclab/PublicLab.Editor/spec/javascripts/button_spec.js (line 7) (1)
```

And repeated for all tests. This suggests that a syntax error prevented the lib from loading at all, perhaps?

**Comment by jywarren** [comment]
Or order of execution maybe?

File: src/modules/PublicLab.RichTextModule.js (hunk 2 above)
Comment (jywarren) [reply src/modules/PublicLab.RichTextModule.js:321]: Aha, can we actually do a comparison nested like this? `(textAreaRect.top || richAreaRect.top) <= (` ? I think we need to split the comparison in 2... i'm just not familiar with this kind of nesting, you may be way ahead of me here... or, possibly, could it be that this is not working in the version of JS/ES or Node that we are using?

**Comment by jywarren** [comment]
So, I highlighted a possible issue above with comparisons in the style:

```node
> (1 || 2) < (3 || 4)
true
```

I'm just not familiar with how JS works in this way, so it' just a guess. But, if it's possibly stopping the tests from being able to load the `PL` object maybe it's an issue.

Also, @Shulammite-Aso -- is this a critical fix holding up https://github.com/publiclab/plots2/pull/8297 ? Or can we just merge that and fix this in follow-up? Thank you!

**Comment by Shulammite-Aso** [comment]
> Also, @Shulammite-Aso -- is this a critical fix holding up publiclab/plots2#8297 ? Or can we just merge that and fix this in follow-up? Thank you!

@jywarren Sorry i reply late. I'll look deeper into all your suggestions, But this isn't a critical bug, the bigger toolbar issue is fixed, just some small glitch with the fix that i think shouldn't stop us from merging publiclab/plots2#8297

**Comment by jywarren** [comment]
Great, thank you @Shulammite-Aso !!

**Comment by sagarpreet-chadha** [comment]
Okay awesome tests are passing 🎉

File: src/modules/PublicLab.RichTextModule.js (hunk 2 above)
Comment (jywarren) [reply src/modules/PublicLab.RichTextModule.js:322]: Hi @Shulammite-Aso could you clarify this just so we can follow the code? It's still a bit confusing to me. Thank you!!!

Comment (Shulammite-Aso) [reply src/modules/PublicLab.RichTextModule.js:322]: Hi @jywarren , So this piece `(textAreaRect.top || richAreaRect.top) <= (` is making the toolbar float for both rich and markdown editing, and it's actually working fine.  I think splitting the comparison in 2 will cause a lot of redundancy, something like this?
`if (
        (textAreaRect.bottom >= ((window.innerHeight || document.documentElement.clientHeight) - footerRect) && textAreaRect.top <= ((window.innerHeight || document.documentElement.clientHeight) - footerRect)) || (richAreaRect.bottom >= ((window.innerHeight || document.documentElement.clientHeight) - footerRect) && richAreaRect.top <= ((window.innerHeight || document.documentElement.clientHeight) - footerRect))
      ) {`
plus it will still actually be nested.  
And not nesting the comparison at all like this `textAreaRect.bottom || richAreaRect.bottom >=` is not producing the wanted result.

I was using `wk-container` , the div that was holding both the `textarea` for markdown and `contenteditable` div for wysiwyg to acheive this result before, but this didn't look too good from plots2, as the  `contenteditable` div is way shorter than `wk-container` div, making the toolbar still begin to float a little before the  `contenteditable` div

**Review by sagarpreet-chadha — APPROVED** [review]
Hey @Shulammite-Aso , 
At a time only `textArearect` or `richArearect` will have value, right? One of them will always have value `null`, right?
Can you just confirm this? Then it is good to go 💯 😄

**Comment by Shulammite-Aso** [comment]
> Hey @Shulammite-Aso ,
> At a time only `textArearect` or `richArearect` will have value, right? One of them will always have value `null`, right?
> Can you just confirm this? Then it is good to go

Yes @sagarpreet-chadha certainly

**Comment by sagarpreet-chadha** [comment]
Okay @Shulammite-Aso , thanks then that condition seems fine 👍 💯

**Comment by jywarren** [comment]
Awesome work and thanks for your patience as we asked for extra info! Merged, congrats!!! 🎉

**Comment by sagarpreet-chadha** [comment]
🎉 🎉 🎉
